version: "3.9"

services:
  backend:
    environment:
      - EXAMPLE_ENV=EXAMPLE
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/root
    ports:
      - "80:80"

